### ISSUE TITLE
FredWalter's checklist

### ISSUE THREAD

**Issue by FredWalter** [githubschool/my-december#11]
- [] learn something to git
- [] learn something else related to git

- [] Create branch
- [] Make changes
- [] Make a commit
- [] push our changes
- [] review a pull request (AKA "PR")
- [] Merge
